let announcements = [
    { id: 1, title: "Semester Registration Deadline", category: "Deadline", audience: "All users", message: "Semester registration closes on 25 January. Students should confirm their unit selections before the deadline.", date: "Today" },
    { id: 2, title: "CAT Timetable Release", category: "Academic", audience: "Students", message: "The first CAT timetable is now available. Departments should brief students on their scheduled assessment dates.", date: "Yesterday" },
    { id: 3, title: "Campus Water Maintenance", category: "Campus", audience: "All users", message: "Water supply will be temporarily interrupted on Saturday from 8:00 AM to 1:00 PM for maintenance.", date: "2 days ago" },
    { id: 4, title: "Innovation Week 2026", category: "Event", audience: "Lecturers", message: "Lecturers are invited to nominate student projects for the Innovation Week exhibition.", date: "4 days ago" }
];
let activeFilter = "all";
let editingAnnouncementId = null;
const categoryIcons = { Academic: "📚", Deadline: "⏳", Campus: "🏫", Event: "🎉" };

function renderAnnouncements() { const list = document.getElementById("announcement-list"); const data = activeFilter === "all" ? announcements : announcements.filter((item) => item.category === activeFilter); if (!data.length) { list.innerHTML = '<div class="empty-state">No announcements in this category.</div>'; return; } list.innerHTML = data.map((announcement) => `<article class="announcement-card ${announcement.category}"><div class="announcement-icon">${categoryIcons[announcement.category]}</div><div class="announcement-content"><div class="announcement-top"><h3>${announcement.title}</h3><span class="badge badge-${announcement.category.toLowerCase()}">${announcement.category}</span></div><p>${announcement.message}</p><div class="announcement-meta">For ${announcement.audience} · Posted ${announcement.date}</div></div><div class="announcement-actions"><button class="btn btn-secondary btn-small" data-action="edit" data-id="${announcement.id}">Edit</button><button class="btn btn-danger btn-small" data-action="delete" data-id="${announcement.id}">Delete</button></div></article>`).join(""); list.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", () => manageAnnouncement(button.dataset.action, Number(button.dataset.id)))); }
function manageAnnouncement(action, id) { const announcement = announcements.find((item) => item.id === id); if (action === "edit") { openModal(announcement); return; } announcements = announcements.filter((item) => item.id !== id); renderAnnouncements(); showToast("Announcement removed."); }
function openModal(announcement) { editingAnnouncementId = announcement?.id || null; document.getElementById("announcement-modal-title").textContent = announcement ? "Edit announcement" : "Post announcement"; document.getElementById("announcement-title").value = announcement?.title || ""; document.getElementById("announcement-category").value = announcement?.category || "Academic"; document.getElementById("announcement-target").value = announcement?.audience || "All users"; document.getElementById("announcement-message").value = announcement?.message || ""; document.getElementById("announcement-modal").classList.add("active"); }
function closeModal() { document.getElementById("announcement-modal").classList.remove("active"); }
function saveAnnouncement() { const title = document.getElementById("announcement-title").value.trim(); const message = document.getElementById("announcement-message").value.trim(); if (!title || !message) { showToast("Add a title and message first."); return; } const entry = { title, message, category: document.getElementById("announcement-category").value, audience: document.getElementById("announcement-target").value }; if (editingAnnouncementId) { Object.assign(announcements.find((item) => item.id === editingAnnouncementId), entry); showToast("Announcement updated."); } else { announcements.unshift({ id: Date.now(), ...entry, date: "Just now" }); showToast("Announcement published."); } closeModal(); renderAnnouncements(); }
function showToast(message) { const toast = document.getElementById("toast"); toast.textContent = message; toast.classList.add("show"); window.setTimeout(() => toast.classList.remove("show"), 2800); }
document.addEventListener("DOMContentLoaded", () => { renderAnnouncements(); document.querySelectorAll(".tab").forEach((tab) => tab.addEventListener("click", () => { document.querySelectorAll(".tab").forEach((item) => item.classList.remove("active")); tab.classList.add("active"); activeFilter = tab.dataset.filter; renderAnnouncements(); })); document.getElementById("open-announcement-modal").addEventListener("click", () => openModal()); document.getElementById("close-announcement-modal").addEventListener("click", closeModal); document.getElementById("save-announcement").addEventListener("click", saveAnnouncement); document.getElementById("announcement-modal").addEventListener("click", (event) => { if (event.target.id === "announcement-modal") closeModal(); }); });
