let courseRecords = [
    { id: 1, course: "BSc Computer Science", unit: "Operating Systems", department: "Computer Science", semester: "Semester 1", year: "2025/2026" },
    { id: 2, course: "BSc Computer Science", unit: "Data Structures", department: "Computer Science", semester: "Semester 1", year: "2025/2026" },
    { id: 3, course: "BSc Information Technology", unit: "Database Systems", department: "Information Technology", semester: "Semester 2", year: "2025/2026" },
    { id: 4, course: "Bachelor of Business", unit: "Principles of Management", department: "Business", semester: "Semester 1", year: "2024/2025" },
    { id: 5, course: "BSc Nursing", unit: "Community Health", department: "Nursing", semester: "Semester 2", year: "2024/2025" }
];
let editingRecordId = null;

function filteredRecords() { const search = document.getElementById("course-search").value.toLowerCase(); const department = document.getElementById("department-filter").value; const year = document.getElementById("year-filter").value; return courseRecords.filter((record) => (record.course.toLowerCase().includes(search) || record.unit.toLowerCase().includes(search)) && (department === "all" || record.department === department) && (year === "all" || record.year === year)); }
function renderRecords() { const body = document.getElementById("courses-body"); const data = filteredRecords(); if (!data.length) { body.innerHTML = '<tr class="empty-row"><td colspan="6">No course records match your filters.</td></tr>'; return; } body.innerHTML = data.map((record) => `<tr><td class="course-title">${record.course}</td><td class="unit-cell">${record.unit}</td><td>${record.department}</td><td>${record.semester}</td><td>${record.year}</td><td><div class="actions"><button class="btn btn-secondary btn-small" data-action="edit" data-id="${record.id}">Edit</button><button class="btn btn-danger btn-small" data-action="delete" data-id="${record.id}">Delete</button></div></td></tr>`).join(""); body.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", () => manageRecord(button.dataset.action, Number(button.dataset.id)))); }
function manageRecord(action, id) { const record = courseRecords.find((item) => item.id === id); if (action === "edit") { openModal(record); return; } courseRecords = courseRecords.filter((item) => item.id !== id); renderRecords(); showToast("Course record deleted."); }
function openModal(record) { editingRecordId = record?.id || null; document.getElementById("course-modal-title").textContent = record ? "Edit course record" : "Add course record"; document.getElementById("course-name").value = record?.course || ""; document.getElementById("unit-name").value = record?.unit || ""; document.getElementById("course-department").value = record?.department || "Computer Science"; document.getElementById("course-semester").value = record?.semester || "Semester 1"; document.getElementById("course-year").value = record?.year || "2025/2026"; document.getElementById("course-modal").classList.add("active"); }
function closeModal() { document.getElementById("course-modal").classList.remove("active"); }
function saveRecord() { const course = document.getElementById("course-name").value.trim(); const unit = document.getElementById("unit-name").value.trim(); if (!course || !unit) { showToast("Enter both a course and unit name."); return; } const entry = { course, unit, department: document.getElementById("course-department").value, semester: document.getElementById("course-semester").value, year: document.getElementById("course-year").value }; if (editingRecordId) { Object.assign(courseRecords.find((item) => item.id === editingRecordId), entry); showToast("Course record updated."); } else { courseRecords.unshift({ id: Date.now(), ...entry }); showToast("Course record added."); } closeModal(); renderRecords(); }
function showToast(message) { const toast = document.getElementById("toast"); toast.textContent = message; toast.classList.add("show"); window.setTimeout(() => toast.classList.remove("show"), 2800); }
document.addEventListener("DOMContentLoaded", () => { renderRecords(); document.getElementById("course-search").addEventListener("input", renderRecords); document.getElementById("department-filter").addEventListener("change", renderRecords); document.getElementById("year-filter").addEventListener("change", renderRecords); document.getElementById("open-course-modal").addEventListener("click", () => openModal()); document.getElementById("close-course-modal").addEventListener("click", closeModal); document.getElementById("save-course").addEventListener("click", saveRecord); document.getElementById("course-modal").addEventListener("click", (event) => { if (event.target.id === "course-modal") closeModal(); }); });
