const chats=[
 {id:'cs',name:'Computer Science Year 3',initials:'CS',tone:'avatar-blue',group:true,online:'24 members online',members:'24',desc:'Semester 1 discussion group',time:'10:42 AM',unread:2,preview:'Mary: The lab instructions are up!',messages:[['James K.','JK','avatar-green','Has everyone seen the updated networks lab instructions?','10:32 AM'],['me','','','Yes, they were posted this morning. I’ll share the link here.','10:36 AM'],['Mary W.','MW','avatar-pink','Thank you Aisha!','10:42 AM']]},
 {id:'mary',name:'Mary Wanjiku',initials:'MW',tone:'avatar-pink',online:'Active now',members:'1',desc:'Computer Science · Year 3',time:'9:18 AM',unread:1,preview:'Can we revise together later?',messages:[['Mary W.','MW','avatar-pink','Hi Aisha! Can we revise database systems together later?','9:14 AM'],['me','','','Definitely. Let’s meet at the library after class.','9:16 AM'],['Mary W.','MW','avatar-pink','Perfect, see you then!','9:18 AM']]},
 {id:'project',name:'Campus Companion Project',initials:'CC',tone:'avatar-purple',group:true,online:'6 members',members:'6',desc:'Software Engineering project team',time:'Yesterday',preview:'Brian: Wireframes are ready for review.',messages:[['Brian M.','BM','avatar-orange','Wireframes are ready for review. I have added them to the shared folder.','Yesterday'],['me','','','Great work! I’ll add feedback before our stand-up.','Yesterday']]},
 {id:'kamau',name:'Dr. Kamau',initials:'DK',tone:'avatar-green',online:'Last seen 35 min ago',members:'1',desc:'Database Systems lecturer',time:'Mon',preview:'Please remember tomorrow’s CAT.',messages:[['Dr. Kamau','DK','avatar-green','Please remember tomorrow’s CAT starts at 9:00 AM.','Mon'],['me','','','Thank you, Doctor.','Mon']]},
 {id:'tech',name:'Code Collective',initials:'⌘',tone:'avatar-orange',group:true,online:'128 members',members:'128',desc:'Official technology club community',time:'Sun',preview:'New hackathon teams are forming.',messages:[['Liam O.','LO','avatar-blue','New hackathon teams are forming. Reply here if you would like to join.','Sun']]},
 {id:'james',name:'James Njoroge',initials:'JN',tone:'avatar-blue',online:'Active now',members:'1',desc:'Database Systems · Year 3',time:'Now',preview:'Your study match is ready to chat.',messages:[['James Njoroge','JN','avatar-blue','Hi Aisha! I saw we share Database Systems and Networks. Want to plan a study session?','Now']]},
 {id:'lilian',name:'Lilian Wambui',initials:'LW',tone:'avatar-pink',online:'Active 12 min ago',members:'1',desc:'Software Engineering · Year 3',time:'Now',preview:'Your study match is ready to chat.',messages:[['Lilian Wambui','LW','avatar-pink','Hello! We seem to have matching project study preferences.','Now']]},
 {id:'brian',name:'Brian Otieno',initials:'BO',tone:'avatar-green',online:'Active now',members:'1',desc:'Computer Networks · Year 3',time:'Now',preview:'Your study match is ready to chat.',messages:[['Brian Otieno','BO','avatar-green','Hi! Ready to compare notes for the networks lab?','Now']]}
];let activeId='cs';let filter='all';const list=document.getElementById('conversation-list');const app=document.querySelector('.chat-app');
function avatar(c,kind='person-avatar'){return `<span class="${kind} ${c.tone}">${c.initials}</span>`}
function renderList(){let q=document.getElementById('chat-search').value.toLowerCase();let shown=chats.filter(c=>(filter==='all'||filter==='groups'&&c.group||filter==='unread'&&c.unread)&&c.name.toLowerCase().includes(q));list.innerHTML=shown.map(c=>`<button class="conversation ${c.id===activeId?'active':''}" data-id="${c.id}">${avatar(c,c.id==='mary'?'person-avatar online':'person-avatar')}<span class="conversation-copy"><strong>${c.name}${c.group?'<small class="group-label"> · GROUP</small>':''}</strong><p>${c.preview}</p></span><span class="conversation-meta">${c.time}${c.unread?`<b class="unread">${c.unread}</b>`:''}</span></button>`).join('')||'<p style="padding:20px;color:var(--muted);font-size:12px">No conversations found.</p>';list.querySelectorAll('.conversation').forEach(b=>b.onclick=()=>openChat(b.dataset.id));updateUnread()}
function openChat(id){activeId=id;let c=chats.find(x=>x.id===id);c.unread=0;document.getElementById('empty-chat').hidden=true;let panel=document.getElementById('active-chat');panel.hidden=false;document.getElementById('chat-name').textContent=c.name;document.getElementById('chat-status').textContent=c.online;document.getElementById('header-avatar').className='chat-avatar '+c.tone;document.getElementById('header-avatar').textContent=c.initials;document.getElementById('info-avatar').className='info-avatar '+c.tone;document.getElementById('info-avatar').textContent=c.initials;document.getElementById('info-name').textContent=c.name;document.getElementById('info-description').textContent=c.desc;document.getElementById('info-members').textContent=c.members;renderMessages();renderList();app.classList.add('chat-open')}
function renderMessages(){let c=chats.find(x=>x.id===activeId),body=document.getElementById('message-body');body.innerHTML='<div class="day-stamp">Today</div>'+c.messages.map(m=>m[0]==='me'?`<div class="message mine"><div class="message-bubble">${m[3]}<span class="message-meta">${m[4]} <i class="read">✓✓</i></span></div></div>`:`<div class="message"><span class="message-face ${m[2]}">${m[1]}</span><div class="message-bubble">${c.group?`<span class="sender">${m[0]}</span>`:''}${m[3]}<span class="message-meta">${m[4]}</span></div></div>`).join('');body.scrollTop=body.scrollHeight}
function updateUnread(){let n=chats.reduce((x,c)=>x+(c.unread||0),0);document.getElementById('unread-count').textContent=n;document.getElementById('side-unread').textContent=n}
document.getElementById('chat-search').oninput=renderList;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelector('[data-filter].active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;renderList()});document.getElementById('message-form').onsubmit=e=>{e.preventDefault();let input=document.getElementById('message-input'),value=input.value.trim();if(!value)return;let c=chats.find(x=>x.id===activeId);c.messages.push(['me','','',value,new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})]);c.preview='You: '+value;c.time='Now';input.value='';renderMessages();renderList();setTimeout(()=>{document.getElementById('typing').hidden=false;setTimeout(()=>{document.getElementById('typing').hidden=true;c.messages.push([c.group?'Mary W.':c.name,c.group?'MW':c.initials,c.group?'avatar-pink':c.tone,'Got it — thanks for the update!','Now']);c.preview='Got it — thanks for the update!';renderMessages();renderList()},1200)},350)};document.getElementById('attach-btn').onclick=()=>toast('File attachment is ready for Firebase Storage');document.getElementById('emoji-btn').onclick=()=>{document.getElementById('message-input').value+=' 😊';document.getElementById('message-input').focus()};document.getElementById('new-chat').onclick=()=>toast('New conversation picker opened');document.getElementById('back-conversations').onclick=()=>app.classList.remove('chat-open');document.getElementById('close-info').onclick=()=>{document.getElementById('chat-info').style.display='none';app.classList.add('info-closed')};const pending=localStorage.getItem('cc_pending_chat');renderList();openChat(pending&&chats.some(c=>c.id===pending)?pending:'cs');localStorage.removeItem('cc_pending_chat');
document.getElementById('new-chat').onclick=()=>{const name=prompt('Who would you like to start a campus chat with?');if(!name?.trim())return;const id='contact-'+Date.now();const initials=name.trim().split(/\s+/).map(n=>n[0]).slice(0,2).join('').toUpperCase();chats.unshift({id,name:name.trim(),initials,tone:'avatar-blue',online:'New campus connection',members:'1',desc:'Campus Companion contact',time:'Now',preview:'Start your conversation.',messages:[]});filter='all';document.querySelector('[data-filter].active').classList.remove('active');document.querySelector('[data-filter="all"]').classList.add('active');openChat(id);toast(`Conversation with ${name.trim()} created`)};document.querySelectorAll('.message-actions button').forEach(b=>b.onclick=()=>toast(`${b.title} request sent`));document.querySelectorAll('.info-action').forEach(b=>b.onclick=()=>{if(b.textContent.includes('Search')){const term=prompt('Search in this conversation');if(term)toast(`Searching messages for “${term}”`)}else toast('Shared files and links panel opened')});
