const PROFILE_KEY = "admin_profile";

function getProfile() { return window.CampusAdmin.getAdminProfile(); }
function renderProfileAvatar(profile) { const avatar = document.getElementById("profile-avatar"); if (!profile.photo) { avatar.textContent = `${profile.firstName[0]}${profile.lastName[0]}`.toUpperCase(); return; } const image = document.createElement("img"); image.src = profile.photo; image.alt = "Admin profile photo"; avatar.replaceChildren(image); }
function loadProfile() { const profile = getProfile(); document.getElementById("first-name").value = profile.firstName; document.getElementById("last-name").value = profile.lastName; document.getElementById("profile-email").value = profile.email; document.getElementById("profile-phone").value = profile.phone; document.getElementById("profile-department").value = profile.department; document.getElementById("profile-bio").value = profile.bio; document.getElementById("profile-name").textContent = `${profile.firstName} ${profile.lastName}`; document.getElementById("profile-department-label").textContent = profile.department; renderProfileAvatar(profile); window.CampusAdmin.hydrateAdminProfile(); }
function saveProfile() { const firstName = document.getElementById("first-name").value.trim(); const lastName = document.getElementById("last-name").value.trim(); if (!firstName || !lastName) { showToast("Enter your first and last name."); return; } const profile = { ...getProfile(), firstName, lastName, email: document.getElementById("profile-email").value.trim(), phone: document.getElementById("profile-phone").value.trim(), department: document.getElementById("profile-department").value, bio: document.getElementById("profile-bio").value.trim() }; localStorage.setItem(PROFILE_KEY, JSON.stringify(profile)); loadProfile(); showToast("Profile saved successfully."); }
function changePhoto(event) { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.addEventListener("load", () => { const profile = { ...getProfile(), photo: reader.result }; localStorage.setItem(PROFILE_KEY, JSON.stringify(profile)); loadProfile(); showToast("Profile photo updated."); }); reader.readAsDataURL(file); }
function updatePassword() { const current = document.getElementById("current-password").value; const next = document.getElementById("new-password").value; const confirm = document.getElementById("confirm-password").value; if (!current || !next || !confirm) { showToast("Fill in all password fields."); return; } if (next !== confirm) { showToast("New passwords do not match."); return; } if (next.length < 6) { showToast("Use at least 6 characters."); return; } document.getElementById("current-password").value = ""; document.getElementById("new-password").value = ""; document.getElementById("confirm-password").value = ""; showToast("Password updated."); }
function showToast(message) { const toast = document.getElementById("toast"); toast.textContent = message; toast.classList.add("show"); window.setTimeout(() => toast.classList.remove("show"), 2800); }
document.addEventListener("DOMContentLoaded", () => { loadProfile(); document.getElementById("save-profile").addEventListener("click", saveProfile); document.getElementById("change-photo").addEventListener("click", () => document.getElementById("photo-input").click()); document.getElementById("photo-input").addEventListener("change", changePhoto); document.getElementById("update-password").addEventListener("click", updatePassword); });
